### ISSUE TITLE
cronjs will not support Internet Explorer 11?

### ISSUE THREAD

**Issue by tnthai** [datasert/cronjs#18]
The matcher seems to be using "Computed property names", but IE11 doesn't support the feature: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer#browser_compatibility

```
const MAX_LOOP_COUNT = 100_000;
const FLD_SECOND = 'second';
const FLD_MINUTE = 'minute';
const FLD_HOUR = 'hour';
const FLD_DAY_OF_MONTH = 'day_of_month';
const FLD_MONTH = 'month';
const FLD_DAY_OF_WEEK = 'day_of_week';
const FLD_YEAR = 'year';
const DAY_SUN = 0;
const DAY_MON = 1;
const DAY_FRI = 5;
const DAY_SAT = 6;

const FIELD_INFO: PlainObject<FieldInfo> = {
  [FLD_SECOND]: {
    min: 0,
    max: 59,
  },
...
```

Same problem in parser. Version 1.1.0.

**Comment by brsanthu** [comment]
@tnthai To be honest, we didn't think about supporting browser in the first place as it was intended for node. That too not IE11 for sure.

For parse, we could somehow make it work for IE11 but don't think we can do that for matcher (which uses Luxon).

**Comment by tnthai** [comment]
@brsanthu Thank you! I did a test and indeed, IE11 seems to have problems with Luxon as well. Maybe they'd stopped supporting old browsers ...
