### ISSUE TITLE
Cronjs matcher does not support cron string with seconds

### ISSUE THREAD

**Issue by ascazzola** [datasert/cronjs#20]
I'm trying to get future matches from a cron expression with seconds, for instance:

`getFutureMatches('0 0/1 * 1/1 * ? * ', {matchCount: 1});`

but I cannot specify the parameter hasSeconds here and it throws an exception

"Invalid cron expression [0 0/1 * 1/1 * ? *]. Expected [4 to 6] fields but found [7] fields."

as a workaround I fixed it calling first the parser and with the parsed expression called the getFutureMatches again.

Is that correct? or you have in mind the possibility to parse cron expressions with 7 positions

**Comment by brsanthu** [comment]
Now you can pass parser options to matcher which includes hasSeconds. For ex., https://github.com/datasert/cronjs/blob/master/packages/matcher/test/unit/matcher.spec.ts#L503
