### ISSUE TITLE
Unexpected milliseconds in getFutureMatches

### ISSUE THREAD

**Issue by mgcrea** [datasert/cronjs#24]
Did not expect to have to consequent `getFutureMatches` calls return different values due to the non null millisecond value:

```
{
  cron: '0 5 * * * *',
  matches: [ '2022-02-18T05:00:00.788Z' ],
  runAt: 2022-02-18T05:00:00.788Z
}
```

```
{
  cron: '0 5 * * * *',
  matches: [ '2022-02-18T05:00:00.958Z' ],
  runAt: 2022-02-18T05:00:00.958Z
}
```

In my case I need strict equality to upsert database records.

**Comment by MarkChrisLevy** [comment]
@brsanthu Hi, could you please publish 1.2.1, as in npm latest version is stil 1.2.0: https://www.npmjs.com/package/@datasert/cronjs-matcher
