### ISSUE TITLE
Why is an "omitted" second field require datetime to have zero sconds?

### ISSUE THREAD

**Issue by FoxxMD** [datasert/cronjs#31]
I want to check if the current time matches a day of the month:

```
* * 15 * ?
```
Date NOW:
```
"2022-09-15T13:30:50.753Z"
```
The `second` field is not defined in the cron expression which treats it as `omit:true` but the [second field matching code](https://github.com/datasert/cronjs/blob/master/packages/matcher/src/matcher.ts#L425) then **requires** that the date object have the second field as `0` -- so `cronjs.isTimeMatches(cron, now)` returns `false`.

This is counter-intuitive...i have not specified the optional second field in the cron expression so why it is being checked at all?

**Comment by brsanthu** [comment]
@FoxxMD If you time, can you pl review PR which fixes this issue? https://github.com/datasert/cronjs/pull/33
