### ISSUE TITLE
Bug: It doesn't parse 7-fields expression

### ISSUE THREAD

**Issue by d00rsfan** [datasert/cronjs#36]
Great project, the only I found, supporting quartz (years). During investigation found bug:
Steps to reproduce, in REPL in directory of project with installed this package:
use string 
0 22 * * */3 * 2023,2020
which is mean 'At 22 minutes past the hour, every 3 months, only in 2023 and 2020'

```
const parser = require('@datasert/cronjs-parser');
> parser.parse('0 22 * * */3 * 2023,2020')
Uncaught:
Error: Invalid cron expression [0 22 * * */3 * 2023,2020]. Expected [4 to 6] fields but found [7] fields.
    at parseExpr
```

**Comment by danmindru** [comment]
hey @d00rsfan you need to specify that it has seconds via the 2nd options param

```js
const parser = require('@datasert/cronjs-parser', { hasSeconds: true });
```
