### ISSUE TITLE
Parser is not erroring on invalid cron expressions with days of month and days of week set.

### ISSUE THREAD

**Issue by phimuskapsi** [datasert/cronjs#48]
Cron Expression Example:
`0 10 * * * *`
This is invalid, you cannot have a wildcard for day of month or week set, yet parser returns a parsed string and expressions with day of month and day of week set to all.

`0 10 10 * * *`
This is invalid as you cannot have a date set and day of the week set to a wildcard

What it seems the code does is returns the pattern and expression, and if you fetch forward matches through matcher, it will display dates as if the day of week is not set at all. This is a pretty large issue.

**Comment by brsanthu** [comment]
> 0 10 * * * *
> This is invalid, you cannot have a wildcard for day of month or week set, yet parser returns a parsed string and expressions with day of month and day of week set to all.

Regd this, [POSIX](https://pubs.opengroup.org/onlinepubs/9699919799.2018edition/utilities/crontab.html) specification for crontab specifies that it is valid. See this [Stackoverflow thread.](https://stackoverflow.com/questions/27412483/how-do-cron-steps-work)

> 0 10 10 * * *
> This is invalid as you cannot have a date set and day of the week set to a wildcard

Regd this, based on the same SO thread analysis, seems like a bug. Will address this in the next version.
